name: Release

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        allowUpdates: true

